classdef CIDKT_LS < Algorithm


    properties (SetAccess = private)
        MuC = 2
        MuM = 5
        KTN = 5
        Delta0 = 0.5
        Gap = 5
        Lambda0 = 0.5
        ParaMin = 0.05
        ParaMax = 0.95
        vartheta = 0.4
        theta  = 0.5
        d_star = 10

        % Large-scale acceleration parameters 
        SubDim = 10         
    end

    methods
        function Parameter = getParameter(Algo)
            Parameter = {'MuC: Simulated Binary Crossover', num2str(Algo.MuC), ...
                'MuM: Polynomial Mutation', num2str(Algo.MuM), ...
                'KTN: Knowledge Transfer Tasks Num', num2str(Algo.KTN), ...
                'Delta0: Initial delta', num2str(Algo.Delta0), ...
                'Gap: Parameter update gap', num2str(Algo.Gap), ...
                'Lambda0: Initial lambda', num2str(Algo.Lambda0), ...
                'ParaMin: Lower bound of parameter', num2str(Algo.ParaMin), ...
                'ParaMax: Upper bound of parameter', num2str(Algo.ParaMax), ...
                'vartheta: Direction consistency threshold', num2str(Algo.vartheta), ...
                'd_star: Number of dominant curvature directions', num2str(Algo.d_star), ...
                'theta: Strength of knowledge transfer', num2str(Algo.theta), ...
                'SubDim: Local evolutionary subspace dimension', num2str(Algo.SubDim)};
        end

        function Algo = setParameter(Algo, Parameter)
            i = 1;
            Algo.MuC      = str2double(Parameter{i}); i = i + 1;
            Algo.MuM      = str2double(Parameter{i}); i = i + 1;
            Algo.KTN      = str2double(Parameter{i}); i = i + 1;
            Algo.Delta0   = str2double(Parameter{i}); i = i + 1;
            Algo.Gap      = str2double(Parameter{i}); i = i + 1;
            Algo.Lambda0  = str2double(Parameter{i}); i = i + 1;
            Algo.ParaMin  = str2double(Parameter{i}); i = i + 1;
            Algo.ParaMax  = str2double(Parameter{i}); i = i + 1;
            Algo.vartheta = str2double(Parameter{i}); i = i + 1;
            Algo.d_star   = str2double(Parameter{i}); i = i + 1;
            Algo.theta    = str2double(Parameter{i}); i = i + 1;

            if length(Parameter) >= i
                Algo.SubDim = max(1, round(str2double(Parameter{i})));
            end
        end

        function run(Algo, Prob)
            % Initialization
            population = Initialization(Algo, Prob, Individual);

            delta = Algo.Delta0 * ones(1, Prob.T);   % probability of selecting SSEI inside inter-task transfer
            lambda = Algo.Lambda0 * ones(1, Prob.T); % probability of selecting intra-task GA search

            Ng = zeros(1, Prob.T); % surviving offspring generated by intra-task GA
            Nb = zeros(1, Prob.T); % surviving offspring generated by SSEI
            Nm = zeros(1, Prob.T); % surviving offspring generated by MGMCE

            prev_best = zeros(1, Prob.T);
            matrix_R = [];
            v_cur = [];


            while Algo.notTerminated(Prob, population)

                % Periodically update curvature directions and task similarity.
                if iteration == 1 || mod(iteration - 1, Algo.Gap) == 0 || isempty(matrix_R)
                    [v_cur, matrix_R] = Algo.CalcTaskSimilarityHessian_LS(population, Algo.d_star);
                end

                % Generation
                [offspring, transferFlag] = Algo.Generation_LS(Prob, population, matrix_R, v_cur, delta, lambda);

                % Evaluation and environmental selection
                for t = 1:Prob.T

                    prev_best(t) = min([population{t}.Objs]); 
                    offspring{t} = Algo.Evaluation(offspring{t}, Prob, t);

                    oldN = length(population{t});
                    population{t} = [population{t}, offspring{t}];

                    [~, rank] = sort([population{t}.Objs]);
                    survivor_idx = rank(1:Prob.N);
                for pos = 1:Prob.N
                      idx = survivor_idx(pos);

                      % Only offspring individuals have indices larger than oldN
                    if idx > oldN
                          k = idx - oldN;

                          % Rank contribution: the better the rank, the larger the contribution
                          rank_score = (Prob.N - pos + 1) / Prob.N;

                          if transferFlag{t}(k) == 0
                              Ng(t) = Ng(t) + 1;
                              Rg(t) = Rg(t) + rank_score;
                          elseif transferFlag{t}(k) == 1
                              Nb(t) = Nb(t) + 1;
                              Rb(t) = Rb(t) + rank_score;
                          elseif transferFlag{t}(k) == 2
                              Nm(t) = Nm(t) + 1;
                              Rm(t) = Rm(t) + rank_score;
                          end
                    end
                end

                    population{t} = population{t}(survivor_idx);
                end

                % Update delta and lambda every Gap generations
                if mod(Algo.Gen, Algo.Gap) == 0

                    for t = 1:Prob.T
                        rho_obs = (Nb(t) ) / (Nb(t) + Nm(t));
                        rho(t) = (1 - 0.2) * rho(t) + 0.2 * rho_obs;
                        rho(t) = min(max(rho(t), Algo.ParaMin), Algo.ParaMax);
                    end

                     for t = 1:Prob.T
                        aux_idx = [1:t-1, t+1:Prob.T];
                        valid_idx = aux_idx(matrix_R(t, aux_idx) > 0);
                        score_aux = matrix_R(t, valid_idx);
                        p_t = score_aux / (sum(score_aux) + 1e-12);
                        S_t = -sum(p_t .* log(p_t + 1e-12)) / log(numel(valid_idx));


                        den_delta = Rg(t) + Rb(t) + Rm(t);

                        if den_delta > 1e-12
                            delta_obs = Rg(t) / den_delta;
                        else
                            delta_obs = delta(t);
                        end

                        delta(t) = (1 - 0.5) * S_t + 0.5 * delta_obs;

                        delta(t) = min(max(delta(t), Algo.ParaMin), Algo.ParaMax);
                    end

                    Ng(:) = 0;
                    Nb(:) = 0;
                    Nm(:) = 0;
                end
            end
        end

        function [offspring, transferFlag] = Generation_LS(Algo, Prob, population, matrix_R, v_cur, delta, lambda)
            offspring = cell(1, length(population));
            transferFlag = cell(1, length(population));

            for t = 1:length(population)
                popSize = length(population{t});
                indorder = randperm(popSize);
                transferFlag{t} = zeros(1, popSize);

                % Target elite set
                targetPop = population{t};
                [~, sort_idx] = sort([targetPop.Objs]);
                elite_num = max(2, ceil(0.2 * numel(targetPop)));
                elitePop = targetPop(sort_idx(1:elite_num));
                eliteDecs = vertcat(elitePop.Dec);
                dim_t = size(eliteDecs, 2);

                mu_e = size(eliteDecs, 1);
                weights = log(mu_e + 0.5) - log(1:mu_e);
                weights = weights / (sum(weights) + 1e-12);

                mu_t = weights * eliteDecs;
                Y = eliteDecs - mu_t;
                Yw = bsxfun(@times, Y, sqrt(weights(:)));
                dist = sqrt(sum(Y.^2, 2));
                elite_scale = weights * dist;

                % Dominant search direction of the target elite set
                if size(Yw, 1) >= 2 && any(abs(Yw(:)) > 1e-12)
                    [~, ~, V] = svd(Yw, 'econ');
                    mainDir = V(:, 1)';
                else
                    mainDir = randn(1, dim_t);
                end
                mainDir = mainDir / (norm(mainDir) + 1e-12);

                % Best solution of target task
                [~, i_best] = min([population{t}.Objs]);
                archive = population{t}(i_best).Dec;
                archive = Algo.AlignDec(archive, dim_t);
                temp_archive = archive;

                % Auxiliary task for SSEI
                scores_ssei = matrix_R(:, t);
                scores_ssei(t) = -inf;
                if all(~isfinite(scores_ssei))
                    rt_ssei = t;
                else
                    [~, rt_ssei] = max(scores_ssei);
                end

                sourcePop = population{rt_ssei};
                [~, idx_s] = min([sourcePop.Objs]);
                best_s = Algo.AlignDec(sourcePop(idx_s).Dec, dim_t);
                v_euc = best_s - archive;

                % Auxiliary tasks and curvature information for MGMCE
                knowledge_task_num = min(Algo.KTN, length(population) - 1);
                scores_mgmce = matrix_R(t, :);
                scores_mgmce(t) = -inf;
                [~, index] = sort(scores_mgmce, 'descend');
                ass_tasks = index(1:knowledge_task_num);

                centerDecs = zeros(knowledge_task_num, dim_t);
                shiftDirs = cell(1, knowledge_task_num);

                for j = 1:knowledge_task_num
                    rt = ass_tasks(j);
                    srcPop = population{rt};
                    [~, idx_src] = min([srcPop.Objs]);
                    centerDecs(j, :) = Algo.AlignDec(srcPop(idx_src).Dec, dim_t);
                    shiftDirs{j} = Algo.AlignDec(v_cur{rt}, dim_t);
                    shiftDirs{j} = shiftDirs{j} / (norm(shiftDirs{j}) + 1e-12);
                end

                shiftDir_t = Algo.AlignDec(v_cur{t}, dim_t);
                shiftDir_t = shiftDir_t / (norm(shiftDir_t) + 1e-12);

                count = 1;
                for i = 1:ceil(popSize / 2)
                    p1 = indorder(i);
                    p2 = indorder(i + fix(popSize / 2));

                    offspring{t}(count) = population{t}(p1);
                    offspring{t}(count + 1) = population{t}(p2);

                    if rand() < lambda(t)
                        % Intra-task GA search
                        transferFlag{t}(count) = 0;
                        transferFlag{t}(count + 1) = 0;

                        [offspring{t}(count).Dec, offspring{t}(count + 1).Dec] = ...
                            GA_Crossover(population{t}(p1).Dec, population{t}(p2).Dec, Algo.MuC);

                        offspring{t}(count).Dec = GA_Mutation(offspring{t}(count).Dec, Algo.MuM);
                        offspring{t}(count + 1).Dec = GA_Mutation(offspring{t}(count + 1).Dec, Algo.MuM);
                    else
                        if rand() < delta(t)
                            % SSEI strategy
                            transferFlag{t}(count) = 1;
                            transferFlag{t}(count + 1) = 1;

                            v_kt = 0.5 * v_euc + 0.5 * shiftDir_t;
                            v_kt = v_kt / (norm(v_kt) + 1e-12);
                            u1 = temp_archive + 0.5 * v_kt;

                            v_euc2 = u1 - temp_archive;
                            v_kt2 = 0.5 * v_euc2 + 0.5 * shiftDir_t;
                            v_kt2 = v_kt2 / (norm(v_kt2) + 1e-12);
                            u2 = u1 + 0.5 * v_kt2;

                            offspring{t}(count).Dec = u1;
                            offspring{t}(count + 1).Dec = u2;

                            temp_archive = u2;
                            v_euc = best_s - temp_archive;
                            v_euc = v_euc / (norm(v_euc) + 1e-12);
                        else
                            % MGMCE strategy
                            transferFlag{t}(count) = 2;
                            transferFlag{t}(count + 1) = 2;

                            parent1 = Algo.AlignDec(population{t}(p1).Dec, dim_t);
                            D_parent = sum((centerDecs - parent1).^2, 2);
                            [~, cluster_id] = min(D_parent);
                            shiftDir = shiftDirs{cluster_id};

                            curvDir = shiftDir / (norm(shiftDir) + 1e-12);
                            dir_sim = abs(dot(curvDir, mainDir));
                            mu_shift = mu_t + Algo.theta * shiftDir;

                            parent2 = Algo.AlignDec(population{t}(p2).Dec, dim_t);
                            D_parent2 = sum((centerDecs - parent2).^2, 2);
                            [~, cluster_id2] = min(D_parent2);
                            shiftDir2 = shiftDirs{cluster_id2};

                            curvDir2 = shiftDir2 / (norm(shiftDir2) + 1e-12);
                            dir_sim2 = abs(dot(curvDir2, mainDir));
                            mu_shift2 = mu_t + Algo.theta * shiftDir2;

                            if dir_sim > Algo.vartheta
                                offspring{t}(count).Dec = Algo.SampleEliteGaussian_LS(mu_shift, Yw);
                            else
                                offspring{t}(count).Dec = Algo.SampleExpandedGaussian_LS(mu_t, Yw, elite_scale, dim_t);
                            end

                            if dir_sim2 > Algo.vartheta
                                offspring{t}(count + 1).Dec = Algo.SampleEliteGaussian_LS(mu_shift2, Yw);
                            else
                                offspring{t}(count + 1).Dec = Algo.SampleExpandedGaussian_LS(mu_t, Yw, elite_scale, dim_t);
                            end
                        end
                    end

                    for x = count:count + 1
                        offspring{t}(x).Dec = Algo.AlignDec(offspring{t}(x).Dec, dim_t);
                        offspring{t}(x).Dec(offspring{t}(x).Dec > 1) = 1;
                        offspring{t}(x).Dec(offspring{t}(x).Dec < 0) = 0;
                    end

                    count = count + 2;
                end
            end
        end

        function [v_cur, R] = CalcTaskSimilarityHessian_LS(Algo, population, d_star)
            T = length(population);
            R = zeros(T, T);
            Infos = cell(1, T);
            v_cur = cell(1, T);

            for t = 1:T
                Infos{t} = Algo.EstimateCurvatureInfo_LS(population{t});
                v_cur{t} = Infos{t}.v_neg;
            end

            for i = 1:T
                R(i, i) = 0;
                for j = i + 1:T
                    sim = Algo.CurvatureInfoSimilarity_LS(Infos{i}, Infos{j}, d_star);
                    R(i, j) = sim;
                    R(j, i) = sim;
                end
            end
        end

        function info = EstimateCurvatureInfo_LS(Algo, pop)
            Decs = vertcat(pop.Dec);
            Objs = vertcat(pop.Objs);

            if size(Objs, 2) > 1
                Objs = sum(Objs, 2);
            end
            Objs = Objs(:);

            d = size(Decs, 2);
            nPop = size(Decs, 1);

            [~, idx_best] = min(Objs);
            center = Decs(idx_best, :);

            Xall = Decs - center;

            % Keep the original local-neighborhood rule.
            nUse = min(nPop, max(65, 4 * d));
            [~, order] = sort(sum(Xall.^2, 2));
            order = order(1:nUse);

            X = Xall(order, :);
            y = Objs(order) - Objs(idx_best);
            y = y(:);

            dist = sqrt(sum(X.^2, 2));
            valid = dist > 1e-10;
            X = X(valid, :);
            y = y(valid);

            if size(X, 1) < 10
                q = randn(d, 1);
                q = q / (norm(q) + 1e-12);

                info.eigvals = 1e-8;
                info.Q = q;
                info.v_neg = q';
                info.dim = d;
                return;
            end

            k = min([Algo.SubDim, d, size(X, 1) - 1]);

            [~, ~, Vpca] = svd(X, 'econ');
            U = Vpca(:, 1:k);

            Z = X * U;
            Phi = Z;

            numPairs = k * (k + 1) / 2;
            quadPairs = zeros(numPairs, 2);
            cnt = 0;

            for a = 1:k
                for b = a:k
                    cnt = cnt + 1;
                    quadPairs(cnt, :) = [a, b];
                    Phi(:, end + 1) = Z(:, a) .* Z(:, b);
                end
            end

            reg = 1e-5;
            beta = (Phi' * Phi + reg * eye(size(Phi, 2))) \ (Phi' * y);

            Hz = zeros(k, k);
            offset = k;

            for q = 1:size(quadPairs, 1)
                a = quadPairs(q, 1);
                b = quadPairs(q, 2);
                coef = beta(offset + q);

                if a == b
                    Hz(a, b) = 2 * coef;
                else
                    Hz(a, b) = coef;
                    Hz(b, a) = coef;
                end
            end

            Hz = (Hz + Hz') / 2;

            % Large-scale key point: eigendecomposition is performed on Hz only.
            [Vz, Dz] = eig(Hz);
            eigvals = diag(Dz);

            Q = U * Vz;
            Q = bsxfun(@rdivide, Q, sqrt(sum(Q.^2, 1)) + 1e-12);

            [~, ord] = sort(abs(eigvals), 'descend');
            eigvals = eigvals(ord);
            Q = Q(:, ord);

            neg_idx = find(eigvals < 0);
            if ~isempty(neg_idx)
                [~, local_idx] = max(abs(eigvals(neg_idx)));
                idx = neg_idx(local_idx);
            else
                [~, idx] = min(eigvals);
            end

            v_neg = Q(:, idx)';
            v_neg = v_neg / (norm(v_neg) + 1e-12);

            info.eigvals = eigvals;
            info.Q = Q;
            info.v_neg = v_neg;
            info.dim = d;
        end

        function sim = CurvatureInfoSimilarity_LS(Algo, info_i, info_j, d_star)
            ei = info_i.eigvals;
            ej = info_j.eigvals;
            Qi = info_i.Q;
            Qj = info_j.Q;

            ri = min([d_star, length(ei), size(Qi, 2)]);
            rj = min([d_star, length(ej), size(Qj, 2)]);

            if ri == 0 || rj == 0
                sim = 0;
                return;
            end

            ei = ei(1:ri);
            ej = ej(1:rj);
            Qi = Qi(:, 1:ri);
            Qj = Qj(:, 1:rj);

            weights = abs(ei);
            if sum(weights) <= 1e-12
                weights = ones(size(weights)) / numel(weights);
            else
                weights = weights / sum(weights);
            end

            targetDim = max(size(Qi, 1), size(Qj, 1));
            align = zeros(ri, 1);

            for a = 1:ri
                vi = Algo.AlignDec(Qi(:, a), targetDim);
                vi = vi / (norm(vi) + 1e-12);

                bestAlign = 0;
                for b = 1:rj
                    vj = Algo.AlignDec(Qj(:, b), targetDim);
                    vj = vj / (norm(vj) + 1e-12);

                    sameCurvature = sign(ei(a)) == sign(ej(b)) || ...
                        abs(ei(a)) <= 1e-12 || abs(ej(b)) <= 1e-12;

                    if sameCurvature
                        bestAlign = max(bestAlign, abs(vi * vj'));
                    end
                end
                align(a) = bestAlign;
            end

            sim = sum(weights(:) .* align(:));

            if ~isfinite(sim)
                sim = 0;
            end

            sim = min(max(sim, 0), 1);
        end

        function x = SampleEliteGaussian_LS(Algo, mu, Yw)
            if isempty(Yw) || ~any(isfinite(Yw(:))) || all(abs(Yw(:)) < 1e-12)
                x = mu + 1e-8 * randn(size(mu));
                return;
            end

            z = randn(1, size(Yw, 1));
            x = mu + z * Yw;
            x = x + 1e-8 * randn(size(mu));
        end

        function x = SampleExpandedGaussian_LS(Algo, mu, Yw, elite_scale, dim)
            x = Algo.SampleEliteGaussian_LS(mu, Yw);

            % This corresponds to adding theta * elite_scale^2 * J to the covariance,
            % where J is the all-one matrix, consistent with Sigma + scalar in MATLAB.
            common_noise = sqrt(max(Algo.theta, 0)) * elite_scale * randn();
            x = x + common_noise * ones(1, dim);
        end

        function x = AlignDec(Algo, x, targetDim)
            x = x(:)';
            if length(x) > targetDim
                x = x(1:targetDim);
            elseif length(x) < targetDim
                x = [x, zeros(1, targetDim - length(x))];
            end
        end
    end
end
